### ISSUE TITLE
App not available in U.S., also alternate download option through web doesn't have English as selectable language.

### ISSUE THREAD

**Issue by NuptupTDOW** [KyneSilverhide/fallout-jdr-helper#16]
![Screenshot_20240121_051707_Google Play Store](https://github.com/KyneSilverhide/fallout-jdr-helper/assets/66802180/13cb461f-28ed-49d8-95d8-046067515934)

![Screenshot_20240121_051914_Chrome](https://github.com/KyneSilverhide/fallout-jdr-helper/assets/66802180/4938c726-39a4-45c0-8b61-a976b11eda98)

**Comment by KyneSilverhide** [comment]
Yes, translation was discontinued, as it would me too much time. Only the menu and interface were translated, but the data was only in french. That's why I removed it from most countries on the play store.
